services:
  - type: web
    name: painel-indicadores-jira
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: PORT
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: EMAIL
        sync: false  # Configure no Dashboard do Render
      - key: TOKEN
        sync: false  # Configure no Dashboard do Render
